### PR TITLE
Added more fixtures

### LINKED ISSUE #995: Create more kinds of fixtures
In GitLab by @JobDoesburg on Jan 29, 2020, 19:41

### One-sentence description

Create fixtures should create fixture for, for example, courses as well.
 
### Motivation

It makes testing easier

### Desired functionality

At least fixtures should be created for courses. But also maybe for photos and albums, documents, payments, registrations?, etc...

### Suggested implementation

### PR DESCRIPTION
**Pull request by 9Y0**
Closes #995 

### Summary
Added fixtures for Courses, Photos + Albums, Payments, Registrations

### How to test
Steps to test the changes you made:
1. Run `./manage.py createfixtures -a`
2. Check the new fixtures on the site

### CODE REVIEW

**Comment by se-bastiaan** [comment]
deploy review

**Comment by se-bastiaan** [comment]
deploy review

**Comment by se-bastiaan** [comment]
@svthalia/server I believe the review environments do not work?

**Comment by joren485** [comment]
remove review

**Comment by se-bastiaan** [comment]
deploy review

**Comment by se-bastiaan** [comment]
remove review

**Pull request merged**
