### PR TITLE
Switch to docker based deployments

### PR DESCRIPTION
**Pull request by pingiun**
### Summary

Adds docker and nixos config to deploy using docker images

### How to test
Try out the deployment on staging

### CODE REVIEW

**Comment by se-bastiaan** [comment]
Do I understand correctly that this defines the following?
 - Our infrastructure is managed through Terraform
 - The server defined in the infrastructure is managed through NixOS config
 - The applications that the NixOS config defines are Docker containers and nginx
 - The concrexit Docker container runs the website

**Comment by pingiun** [comment]
> Do I understand correctly that this defines the following?
> 
> * Our infrastructure is managed through Terraform
> * The server defined in the infrastructure is managed through NixOS config
> * The applications that the NixOS config defines are Docker containers and nginx
> * The concrexit Docker container runs the website

yes

**Comment by JobDoesburg** [comment]
I just thought about it again and I think we shouldn't use nix at all. It might be a nice tool for the job, and this is already way more readable than what we had, but just isn't maintainable, as there are so little people that know anything about nix.

**Comment by pingiun** [comment]
I don't want to go back to ansible

**Comment by JobDoesburg** [comment]
> I don't want to go back to ansible

That's true, and I agree that this concrexit-server.nix is pretty well readable. But isn't it easier to just do it manually?

**Comment by JobDoesburg** [comment]
Nvm maybe lets just keep it this way... The comments in nix help a lot

**Comment by se-bastiaan** [comment]
I like it, quite understandable and seems easy to still do quick deployments like this and change the server config. Highly prefer this over ansible as well.

**Review by se-bastiaan — APPROVED** [review]

**Pull request merged**
