### PR TITLE
Fix leap year problem not being able to view mentor profiles

### PR DESCRIPTION
**Pull request by T8902**
### Summary

Profiles broke due to the leap year. This should now be fixed

### CODE REVIEW

**Review by Noah-marc — COMMENTED** [review]
Hupsi, I did not see that tests were failing. I don't really understand why the tests are failing suddenly tho.

@T8902 & @DeD1rk do you have an idea ?

**Comment by DeD1rk** [comment]
@Noah-marc test failures are a leap year problem

**Comment by DeD1rk** [comment]
Test failure mught be different leap yer problems that occur only in test code

**Comment by Noah-marc** [comment]
Yeah the tests fail because the year in the tests is not a leap year and thus querying the 29th fails. 
So it is actually a test that could only fail once ever 4 years. Lol 

I think it is fixed by simply making sure the test uses a leap year as well

**Comment by DeD1rk** [comment]
Yup, tests can be updated to not use timezone.now().replace(year=...) or similar in a separate PR

**Review by DeD1rk — APPROVED** [review]

**Pull request merged**
