### PR TITLE
Add user registration to events API v2 for cancelled situations

### LINKED ISSUE #1863: Add cancelled registrations to event in api v2
### Is your feature request related to a problem? Please describe.
API v2 doesn't return a cancelled registration when you've cancelled a registration (in the event serializer). So we cannot display stuff like 'Your registration is cancelled (after the deadline)'.

### Describe the solution you'd like
Also return a registration if it's cancelled, and include fields like is_cancelled, is_late_cancellation, etc.

### Motivation
This makes it possible to show nice status texts like in the old app and the website.

### Describe alternatives you've considered
Leaving out the messages for cancelled registrations. In that case, you can only see that there is no register button, but not why.

### PR DESCRIPTION
**Pull request by se-bastiaan**
Closes #1863

### Summary
Add user registration to events API v2 for cancelled situations

### How to test
Steps to test the changes you made:
1. Go to /api/docs
2. Check api v2 event registrations for users in the event serializer

### CODE REVIEW

**Comment by JobDoesburg** [comment]
Maybe we want to have api filters on this?

**Comment by se-bastiaan** [comment]
> Maybe we want to have api filters on this?

I do not understand your question, what do you want to filter on exactly?

**Comment by JobDoesburg** [comment]
> > Maybe we want to have api filters on this?
> 
> I do not understand your question, what do you want to filter on exactly?

Filter on whether we want to include cancelled registrations or not.

**Comment by se-bastiaan** [comment]
> 
> 
> > > Maybe we want to have api filters on this?
> > 
> > 
> > I do not understand your question, what do you want to filter on exactly?
> 
> Filter on whether we want to include cancelled registrations or not.

@JobDoesburg That has nothing to do with this issue >.< This is about showing the cancelled registration from the user itself. We already have a filter in the admin API: https://github.com/svthalia/concrexit/blob/master/website/events/api/v2/admin/filters.py#L29

**Review by DeD1rk — APPROVED** [review]

**Pull request merged**
