### PR TITLE
Add placeholders for discord and online locations

### LINKED ISSUE #1465: Set a placeholder image for the location 'online'
### Is your feature request related to a problem? Please describe.
So many events are online now and it is confusing for me that the location on the Map shows this location in Arkansas, USA
online

### Describe the solution you'd like
We should have a nice online image that we can show if the location is 'online'. And maybe also an image for the location 'discord'?

discord
Artboard 19

### Motivation
Nice to have.

### Describe alternatives you've considered
Not doing anything.

### PR DESCRIPTION
**Pull request by se-bastiaan**
Closes #1465 

### Summary
Add placeholders for discord and online locations.

### How to test
Steps to test the changes you made:
1. Go to an event and set the location for the minimap to 'online'
2. Check that the correct placeholder is shown
3. Repeat the steps above for the location text 'discord'

### CODE REVIEW

**Review by pingiun — CHANGES_REQUESTED** [review]
This seems like a smart idea, but I think you should also add information text to the admin so people know this is possible.

**Comment by pingiun** [comment]
Also I propose this image for the online minimap:

image

(/s)

**Comment by se-bastiaan** [comment]
> This seems like a smart idea, but I think you should also add information text to the admin so people know this is possible.

I was planning on sending an email to committee chairs instead so that they know. Most of them already use this kind of locations.

**Comment by pingiun** [comment]
I think adding the help text is still beneficial

**Review by pingiun — APPROVED** [review]

**Pull request merged**
