### PR TITLE
Fix renewal form

### PR DESCRIPTION
**Pull request by se-bastiaan**
### Summary

The renewal form had a required `contribution` field after #1054 without default, which made it impossible to create regular membership renewals

### How to test
Steps to test the changes you made:
1. Go to the membership renewal page and make sure you can renew
2. Try to renew a membership with type member
3. Try to renew a membership with type benefactor
4. Try the above but with a different value in the contribution field

### CODE REVIEW

**Comment by JobDoesburg** [comment]
Right now I can only request a member renewal, not benefactor, because it now required the length field to be filled

**Comment by se-bastiaan** [comment]
Do you have javascript competely enabled? The value of the length field is automatically set to 'year' when you switch to benefactor.

**Comment by JobDoesburg** [comment]
I do have enabled javascript but it still doesn't work properly for me... Maybe it is specific to my browser or something...

**Comment by se-bastiaan** [comment]
deploy review

**Comment by se-bastiaan** [comment]
@JobDoesburg Can you try the review env? What browser?

**Comment by JobDoesburg** [comment]
remove review

**Review by JobDoesburg — APPROVED** [review]

**Pull request merged**
