### PR TITLE
Add NixOS test

### LINKED ISSUE #1464: Add testing to see if pages load correctly
### Is your feature request related to a problem? Please describe.
As #1461 showed, it seems that it is possible for fairly critical page load errors (in this case, `GET /events/`) to slip through testing.

### Describe the solution you'd like
I would like more tests added, to increase robustness and reduce the chance of an edit of templates etc to break pages. In this case, it would be adding tests to see if pages load correctly.

### Motivation
#1461 showed that this can be a real issue. Making sure that testing is comprehensive can prevent issues like this from getting merged in the future.

### PR DESCRIPTION
**Pull request by pingiun**
Closes #1464 

### Summary
NixOS has a testing module where you can write python scripts to test an actual system (running as a VM). I added a test that requests pages from the sitemap and checks if they return a succesful page.

### How to test
We cannot test this yet as GitHub Actions does not have the ability to start up a VM

### CODE REVIEW

**Comment by pingiun** [comment]
I based this branch on refactor-settings2 (#1459) because then I don't have to change nix things after that is merged

**Review by se-bastiaan — COMMENTED** [review]
I don't entirely get why this has to be a Nix test, wouldn't it be perfectly fine to be a general test module. The code you wrote is Python already and having tests to test Django in Nix doesn't really make it easier to understand what is happening.

**Comment by pingiun** [comment]
This PR is succeeding on hydra: https://hydra.technicie.nl/jobset/concrexit/1477 (see also the github status checks)

**Comment by se-bastiaan** [comment]
But it shows a 502 error and the other tests fail :p

**Review by se-bastiaan — APPROVED** [review]

**Pull request merged**
