### PR TITLE
Change text of registrations payment email

### PR DESCRIPTION
**Pull request by se-bastiaan**
See https://github.com/svthalia/concrexit/pull/1185

### CODE REVIEW

**Comment by JobDoesburg** [comment]
Has the candiboard been involved in these texts? I don't know what they're planning on with corona next year at all regarding use of the board room and merc in general

**Comment by pingiun** [comment]
Nick told me that he has discussed this with Kimberley

**Comment by pingiun** [comment]
I got a single question in the mail about what should be entered in the "Name" field for a bank transfer. I think that can be added easily, but it is probably not a priority as I believe the name is not checked anywhere in the banking system

**Comment by se-bastiaan** [comment]
This has already been deployed to production. Nick made the changes to the texts and I committed those.
If the 30th wants to make other changes we can always do that later.

**Pull request merged**
