### PR TITLE
Add support for multiple local partners

### LINKED ISSUE #2041: Add support for multiple local partners
### Is your feature request related to a problem? Please describe.
We really want to be able to have multiple local partners at Thalia. And the website current does not support this.

### Describe the solution you'd like
We would like the ability to add multiple local partners.

### Motivation
We think it's useful to have multiple local partners so we can show our students what is available in Nijmegen.

### Describe alternatives you've considered
Only having one local partner, which does not make sense in the current partner climate.

### Additional context
The local partner is also shown in the newsletter.

### PR DESCRIPTION
**Pull request by wdoeland**
See #2041 

### Summary
Add support for multiple local partners instead of just one.

### How to test
Steps to test the changes you made:
1. Go to 'site admin -> partners'
2. Make sure two or more partners are set as local partner
3. Go to the partner page on the website
4. See two local partners on the website
7. Check if steps 3-4 work with one local partner

### CODE REVIEW

**Comment by pingiun** [comment]
deploy review

**Comment by pingiun** [comment]
remove review

**Review by se-bastiaan — APPROVED** [review]

**Comment by se-bastiaan** [comment]
The logos can become very large in usage, maybe we want to make those a bit smaller? But it works, can improve later anyways.

**Comment by wdoeland** [comment]
> The logos can become very large in usage, maybe we want to make those a bit smaller? But it works, can improve later anyways.

We can fix that later, I think.

> Maybe don't close the issue yet tho?

Fixed that!

**Pull request merged**
