### PR TITLE
Use CSS variables for dark mode

### LINKED ISSUE #1100: Use CSS variables for dark mode
### Describe the change
Use CSS variables instead of SASS variables for our colour schemes like changing dark mode.

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
https://sparanoid.com/note/css-variables-guide/
https://engineering.fb.com/web/facebook-redesign/

### Motivation
It would mean less files to maintain and 77KB less to load on first page visit.

### Current implementation
Currently we have two CSS files that are compiled from our SASS code, one for light and one for dark mode. This results in the user's browser loading two files. Since they are compiled and compressed they are just 77KB. But there are still two files and the current configuration is quite complex for first time SASS users. 

### Suggested implementation
Use the CSS variables and have only one single 'main' SASS file that switches between the colour variables. The urls above should give a good idea on how this works.

### PR DESCRIPTION
**Pull request by chrysillala**
Closes #1100 

### Summary
Refactor SASS variables to CSS variables for colour schemes

### CODE REVIEW

**Review by se-bastiaan — APPROVED** [review]

**Comment by chrysillala** [comment]
Hi @se-bastiaan, could you please help me to add `hacktoberfest-accepted` label to this PR? As I will need it order to complete my participation in Hacktoberfest. Thanks!

**Comment by se-bastiaan** [comment]
@chrysillala ah it seems that it was affected by me removing the topic from the whole repo, I have re-added that. I think that [should also work](https://hacktoberfest.digitalocean.com/hacktoberfest-update). Let me know!

**Comment by chrysillala** [comment]
@se-bastiaan I still get the `Ineligible Repository` mark, could you please try to add `hacktoberfest-accepted` label to this PR as mentioned below? Thanks!

**Ineligible Repository**
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by chrysillala** [comment]
Hi @se-bastiaan, sorry for disturbing you again. May I know when did you remove the topic from the whole repo? Will need this as a proof to show that my PR is valid. Thanks :)

**Comment by se-bastiaan** [comment]
Monday evening somewhere somewhere after 20:00 CET

**Comment by se-bastiaan** [comment]
@chrysillala Did it all work out?

**Comment by chrysillala** [comment]
@se-bastiaan unfortunately no, I tried to contact the Hacktoberfest team and this is what they told me..
`It looks like the `hacktoberfest` topic was removed from the repository before your PR completed its review period.`

**Pull request merged**
