### PR TITLE
Social media links in newsletters

### LINKED ISSUE #2164: Social media links in newsletters
### Is your feature request related to a problem? Please describe.
We have social media channels, they can be added to the newsletter

### Describe the solution you'd like
Add them to the footer

### PR DESCRIPTION
**Pull request by Gulianrdgd**
Closes #2164

### Summary
Added social media links and logos to the bottom of the email template

### How to test
Steps to test the changes you made:
1. Go to 'newsletters'
2. Click on 'a newsletter'
3. Click on 'show preview'

### CODE REVIEW

**Review by pingiun — APPROVED** [review]
I like how this looks, very nice:

image

**Comment by Gulianrdgd** [comment]
Oops, its back up again

**Comment by JobDoesburg** [comment]
Wait I just figured that .svg's are not supported by a lot of mail clients ... (see https://css-tricks.com/a-guide-on-svg-support-in-email/) @pingiun

**Comment by pingiun** [comment]
sad

**Comment by JobDoesburg** [comment]
@Gulianrdgd can you reopen and replace the .svgs with .pngs?

**Pull request merged**
