### PR TITLE
Add photos API v2

### PR DESCRIPTION
**Pull request by se-bastiaan**
Part of #1428

### Summary
Add photos API v2

### How to test
Steps to test the changes you made:
1. Check the API docs
2. Check the endpoints for the photos

### CODE REVIEW

**Comment by KiOui** [comment]
deploy review

**Comment by se-bastiaan** [comment]
remove review

**Comment by KiOui** [comment]
deploy review

**Comment by KiOui** [comment]
remove review

**Comment by KiOui** [comment]
deploy review

**Comment by pingiun** [comment]
The reviewhost isn't working because this branch is not based on fix #1510

**Comment by se-bastiaan** [comment]
remove review

**Comment by se-bastiaan** [comment]
deploy review

**Review by KiOui — APPROVED** [review]

**Comment by KiOui** [comment]
remove review

**Pull request merged**
