### PR TITLE
email changed

### LINKED ISSUE #3490: Different email for trust contact person Lisa
### What?

The email of Lisa is not her preferred email and she wants this changed .

### Why?

The personal email is not the preferred email right for things like this to be send too.

### How?

Change the email.

### PR DESCRIPTION
**Pull request by T8902**
Closes #3490.

### Summary

Changed the email of TCP lisa

### CODE REVIEW

**Review by DeD1rk — CHANGES_REQUESTED** [review]
All of the indentation changed while it's just a single line that actually has to change.

**Comment by T8902** [comment]
> All of the indentation changed while it's just a single line that actually has to change.
Oh kut black formatted it weird didn't see that

**Comment by DeD1rk** [comment]
But also, IIRC it was intentional that TCPs don't use their `@ru.nl` email: the conversations are confidential, so shouldn't be in a university-managed mailbox (and more importantly, definitely not in an `@members.thalia.nu` mailbox). I'm not sure if this has been noted anywhere, but did lisa consider it?

**Comment by T8902** [comment]
> But also, IIRC it was intentional that TCPs don't use their `@ru.nl` email: the conversations are confidential, so shouldn't be in a university-managed mailbox (and more importantly, definitely not in an `@members.thalia.nu` mailbox). I'm not sure if this has been noted anywhere, but did lisa consider it?



Doubt she considered it, I'll discuss the necessity again with her.

**Comment by DeD1rk** [comment]
I can't find anything about it in any minutes or reports, and it probably doesn't matter (the uni's professional confidential advisors also use @ru.nl) but for the sake of being accessible and not sounding official (as technically TCPs are supposed to mainly refer to the right trained professional), I think having personal addresses would still be preferable.

**Comment by T8902** [comment]
After further discussion, the email will be changed later to an email that isn't @ru.nl however not right now.

**Pull request closed without merging**
