### PR TITLE
Make Oauth authorization pages left-aligned

### PR DESCRIPTION
**Pull request by JobDoesburg**
### Summary
Make Oauth authorization pages left-aligned

### How to test
1. Authorize an OAuth application
2. View authorized applications
3. Delete authorized applications again

### CODE REVIEW

**Comment by se-bastiaan** [comment]
Screenshot? :)

**Comment by JobDoesburg** [comment]
afbeelding

**Comment by JobDoesburg** [comment]
Nvm I just tried it on desktop and it doesnt look optimal yet

**Comment by JobDoesburg** [comment]
afbeelding
afbeelding
afbeelding

**Review by pingiun — APPROVED** [review]
Looks nice!

**Pull request merged**
