### PR TITLE
Delete payments on FoodOrder update via API

### LINKED ISSUE #1783: Food order can be changed after paying
### Describe the bug
If you order a pizza and pay it, you can still change the product. If you change the product through the api, the payment is not removed.

### How to reproduce
Steps to reproduce the behaviour:
1. Order a pizza
2. Pay with Thalia Pay
3. Change the order through the api
4. Get an expensive pizza for little money

### Expected behaviour
Either changing the order after paying is impossible, or it removes the payment. I think removing the payment (as the website currently seems to do) would be strange, and for event registration we've decided not to enable this.

### Screenshots
image

There are probably no food events any time soon, so a hotfix may not be needed, though it might be good to double-check that similar stuff is not possible with registrations.

### PR DESCRIPTION
**Pull request by JobDoesburg**
Closes #1783

### Summary
Adds a check to the FoodOrderDetail API view that tries to delete a payment if the order is updated

### How to test
1. Have a food order
2. Pay it with Thalia Pay
3. Change to a more expensive pizza
4. The payment is gone (or the update is not accepted)

### CODE REVIEW

**Comment by DeD1rk** [comment]
I think something else is the real problem: https://github.com/svthalia/concrexit/blob/6a42032f4ffadf993267b6cacce0ccf7a493df0d/website/pizzas/models.py#L249 
the order model's can_be_changed is true when paid with TPay. Both the website and the api should probably use that property, as in https://github.com/svthalia/concrexit/blob/6a42032f4ffadf993267b6cacce0ccf7a493df0d/website/pizzas/views.py#L54

Although I think this PR does solve the problem in the API, it's probably better to fix the `can_be_changed` for both website and API.

**Comment by DeD1rk** [comment]
Also, do we want it to be possible to change a paid order at all? It feels vague to try to remove the payment ("if you pay you might be able to change your order later, but we're not sure"). I think it would be more logical to just forbid changing orders after paying, unless the "payment can't be removed" case will normally never occur.

**Comment by JobDoesburg** [comment]
The thing is that people at borrels are drunk and they will order a pizza and immediately pay with Thalia Pay, with the consequence that they will not be able to change the order anymore. Better UX would be that they can still try to change their order if it's possible. 

I do agree that we should implement something at the model level. That would be immutable payables, #1772 and #1766.

But for now I think it is a proper fix that implements exactly the same as the html view

**Comment by DeD1rk** [comment]
> people at borrels are drunk 

Fair enough, then the `can_be_changed` is also correct for now.

**Review by DeD1rk — APPROVED** [review]

**Pull request merged**
