### PR TITLE
Display random current summaries instead of always the latest

### PR DESCRIPTION
**Pull request by JobDoesburg**
### Summary
Display random current summaries instead of always the latest

### CODE REVIEW

**Comment by pingiun** [comment]
The header will still say "recent"

**Comment by JobDoesburg** [comment]
> The header will still say "recent"

Same for vacancies

**Comment by se-bastiaan** [comment]
That was a deliberate choice so that all partners are happy :) 

Maybe it would be nice if the summaries are actually recent? Choose some random options from the 25 last uploaded documents or something?

**Comment by JobDoesburg** [comment]
I did filter on courses that 'exist', but maybe I could choose the most recent document per course or something

**Pull request closed without merging**
