### PR TITLE
Update header photos

### LINKED ISSUE #2318: Change the header photos
### Is your feature request related to a problem? Please describe.
The header photos are a bit outdated 

### Describe the solution you'd like
Choose some new photos

### Motivation
image
these guys are old
image
this image is lowres and old

### Describe alternatives you've considered
Not

### Additional context
I have access to the RU Brandportal with nice stock images of the university that we can use

### PR DESCRIPTION
**Pull request by NienkeWessel**
Closes #2318 #3461 .

### Summary
- Changed headers on standard pages by adding a few banners and deleting old ones
- Photos pages now have random headers as well, but from a different subset of headers

Main philosophy is that the photos section (being behind a login) can have fun photos of events, whereas most pages of the website should have more serious photos because everyone can see those. 

### How to test
1. Open website
2. Refresh random pages to see if all photos work 
3. Go to the photos pages, refresh multiple times to see if all photos work

### CODE REVIEW

**Comment by NienkeWessel** [comment]
It should perhaps be noted that Job's problem in #2318 is not completely solved, as the new banners are often not of sufficient quality for high res screens either (although the resolution of the new banners is considerably higher than the old ones). This problem sadly cannot be solved without access to very high resolution pictures.

**Comment by DeD1rk** [comment]
Very nice! I like the very high quality these have.

Having 5K headers does come with the downside of the files being large and hence slow. Perhaps we could provide +-1200 wide versions as well using <picture>? That's a bit more of a change though

**Comment by NienkeWessel** [comment]
@DeD1rk I am not quite sure how that would work, but be my guest if you'd want to implement that.
If I can help by supplying the banners in different formats/resolutions, let me know

**Comment by DeD1rk** [comment]
I upscaled the old remaining banners, and provided them in 2k and 5k width WebPs. While many browsers always prefer '3x' resolution images, we do now support picking the smaller files, e.g. on smaller phones

**Review by DeD1rk — APPROVED** [review]

**Pull request merged**
