### PR TITLE
Fix "complex_logic" issue in website/activemembers/models.py

### LINKED ISSUE #1122: Fix "complex_logic" issue in website/activemembers/models.py
Consider simplifying this complex logical expression.

https://codeclimate.com/github/svthalia/concrexit/website/activemembers/models.py#issue_5ece5c04bce51d000100032a

### PR DESCRIPTION
**Pull request by pingiun**
Closes #1122 

### Summary
Fixed a "complex logic" codeclimate issue

### How to test

Test suite covers this code

### CODE REVIEW

**Comment by pingiun** [comment]
Converted to draft because there is a very similar issue in the same file that I missed

**Comment by pingiun** [comment]
This introduces a new codeclimate issue for my new function, but I believe it has less "Cognitive Complexity" than the previous solution and it's thoroughly documented

**Comment by se-bastiaan** [comment]
deploy review

**Comment by se-bastiaan** [comment]
remove review

**Pull request merged**
