### PR TITLE
Generate model relation diagram in CI

### LINKED ISSUE #2840: Model Relation Diagram generation with GraphViz
### Is your feature request related to a problem? Please describe.
Generate a diagram from the model layer in the pipeline

### Motivation
Automatic Documentation is good

### Describe alternatives you've considered
Manual labor

### Additional context
I will implement this feature

`python manage.py graph_models -a -g -o models.png` requires: https://graphviz.org/download/
https://django-extensions.readthedocs.io/en/latest/graph_models.html

### PR DESCRIPTION
**Pull request by mark-boute**
Closes #2840

### Summary
Requires [GraphViz](https://graphviz.org/download/)
Create workflow that generates a graph png file (could be dot) of the selected application models (all for now).
For configuration see: [django_extensions graph_model](https://django-extensions.readthedocs.io/en/latest/graph_models.html#default-settings)

### How to test
1. Create a PR
2. See a correct model in models_graph.png

For the commit that fixed the poetry.lock conflict:
[Actions run](https://github.com/svthalia/concrexit/actions/runs/4417743204)

### CODE REVIEW

**Comment by mark-boute** [comment]
@JobDoesburg I am kind of stuck, is it even possible to allow the GH Workflow to actually update the `models_graph.png` file?

**Comment by JobDoesburg** [comment]
Yes and no, GH can't easily commit files.

**Comment by mark-boute** [comment]
Should I add the model generation to the pre-commit hook instead? This will add a dependency 
Or just add a make command instead?

**Comment by JobDoesburg** [comment]
I think the best thing to do is write a GitHub action that generates the image and uploads it as artefact to the result of the action, similar to what we do with coverage reports.

**Review by JobDoesburg — APPROVED** [review]
Looks good!

**Pull request merged**
